### ISSUE TITLE
Possible Version Mismatch? 

### ISSUE THREAD

**Issue by Coolfeather2** [cybertiger/Bukkit-InstantReset#12]
At Launch:

```
[17:59:52 INFO]: [InstantReset] Enabling InstantReset v1.10-antony
[17:59:52 ERROR]: Error occurred while enabling InstantReset v1.10-antony (Is it up to date?)
java.lang.NullPointerException
        at org.cyberiantiger.minecraft.instantreset.libnbt.unsafe.v1_8_R3.InstanceTools.createInstance(InstanceTools.java:69) ~[?:?]
        at org.cyberiantiger.minecraft.instantreset.InstantReset.loadWorld(InstantReset.java:160) ~[?:?]
        at org.cyberiantiger.minecraft.instantreset.InstantReset.reloadWorld(InstantReset.java:207) ~[?:?]
        at org.cyberiantiger.minecraft.instantreset.InstantReset.onEnable(InstantReset.java:100) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-76236cb-d4e32ce]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
```

Running /ir reset the_end

```
org.bukkit.command.CommandException: Unhandled exception executing command 'ir' in plugin InstantReset v1.10-antony
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-76236cb-d4e32ce]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-76236cb-d4e32ce]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-76236cb-d4e32ce]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NullPointerException
        at org.cyberiantiger.minecraft.instantreset.libnbt.unsafe.v1_8_R3.InstanceTools.createInstance(InstanceTools.java:69) ~[?:?]
        at org.cyberiantiger.minecraft.instantreset.InstantReset.loadWorld(InstantReset.java:160) ~[?:?]
        at org.cyberiantiger.minecraft.instantreset.InstantReset.resetWorld(InstantReset.java:217) ~[?:?]
        at org.cyberiantiger.minecraft.instantreset.ResetSubCommand.onCommand(ResetSubCommand.java:43) ~[?:?]
        at org.cyberiantiger.minecraft.instantreset.InstantReset.onCommand(InstantReset.java:138) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-76236cb-d4e32ce]
        ... 8 more
```

Config:

```
# Where to look for world templates.
templatedir: templates 
# Where to store temporary files for instantreset worlds.
worlddir: worlds
# Reset worlds on restart
resetOnRestart: false
# List of resetable worlds
#
# Note: they will not load if they are invalid, and messages as
# to why the did not load will be printed to the console.
#
# The environment must match the world save or you will end up
# with an empty world.
#
# You cannot (yet) use this plugin to reset the default worlds in 
# CraftBukkit, as the unload API prevents them from being unloaded.
worlds:
    # Name of world.
    the_end:
        # Name of directory containing the world save.
        template: "world_the_end"
        # Environment, one of NORMAL, NETHER, THE_END
        environment: THE_END
        # Difficulty, one of EASY, NORMAL, HARD, PEACEFUL
        difficulty: NORMAL
```

**Comment by Coolfeather2** [comment]
Not used anymore
